import Link from 'next/link';
// import { Head } from 'next/document';
// <Head>
//   <title>Create Next App</title>
//   <meta name="description" content="Generated by create next app"/>
//   <link rel="icon" href="../public/favicon.ico"/>
// </Head>
export function MainLayout({ children, title = 'Next app' }) {
  return (
    <>

      <nav>
        <h1>Navigation</h1>
        <Link href={'/'}><a> Home </a></Link>
        <Link href={'/about'}><a> About </a></Link>
        <Link href={'/post'}><a> Post </a></Link>
      </nav>
      <main>
        {children}
      </main>
      {/*   <style jsx global>  global i  depqum  styler@  globalen  darnum  bolor  nav  eri  hamar   */}
      <style jsx >
        {` nav {
          height: 60px;
          width: 100%;
          background: darkblue;
          display: flex;
          justify-content: space-around;
          align-items: center;
          text-transform: capitalize;
        }

        nav a {
          color: #eaeaea;
          text-decoration: none;
        }

        nav h1 {
          color: #eaeaea;
        }
        `}
      </style>
    </>
  );
}
